version: '3.8'

volumes:
    mysql:
        driver: local

networks:
    laravel:
        driver: bridge

services:
    mysql:
        image: "mysql:8.0"
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - laravel
    php:
        build:
            context: .docker/php # ~.docker/php/Dockerfile
        ports:
            - "8080:80"
        restart: always
        volumes:
            -   .:/var/www/html
        networks:
            - laravel
